# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Clipboard Manager: CopyQ (primary clipboard manager with history)
exec-once = copyq &
