[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\t/home/sam)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3\xc2\0\0\0#\0\0\a|\0\0\x2)\0\0\x3\xc2\0\0\0#\0\0\a|\0\0\x2)\0\0\0\0\0\0\0\0\a\x80\0\0\x3\xc2\0\0\0#\0\0\a|\0\0\x2))

[FullScreen]
pos=@Point(0 0)
screen=@Rect(0 0 0 0)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(600 0)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[RecentsMRL]
list=file:///home/sam/journaling/2026-05-07%2015-30-46.mp4, file:///home/sam/journaling/2026-05-07%2015-25-55.mp4, file:///home/sam/journaling/2026-01-02%2019-42-20.mp4, file:///home/sam/2026-01-01%2020-00-10.mp4, file:///home/sam/2025-12-29%2010-30-19.mp4, file:///home/sam/Downloads/MasterClass%20-%20Garry%20Kasparov%20Teaches%20Chess%20%282017%29%20%28720p%29/01.%20MasterClass%20-%20Garry%20Kasporov%20Teaches%20Chess%20-%20Introduction.mkv, file:///run/media/sam/EOS_DIGITAL/PRIVATE/AVCHD/BDMV/MOVIEOBJ.BDM, file:///run/media/sam/EOS_DIGITAL/PRIVATE/AVCHD/BDMV/CLIPINF/00001.CPI, file:///run/media/sam/EOS_DIGITAL/PRIVATE/AVCHD/BDMV/CLIPINF/00000.CPI
times=5400, 0, 0, 0, 14650, 0, 0, 0, 0
